<h2 class="text-center">Eliminar Canción</h2>
        <form id="eliminar-cancion" method="post" action="deleteSong">
            <div class="mb-3">
                <label for="songSelect" class="form-label">Canción a eliminar</label>
                <select class="form-control" id="songSelect" name="song_id">
                    <option value="" disabled selected>Selecciona una canción</option>
                    <?= $options ?>
                </select>
            </div>
            <button type="submit" class="btn btn-primary">Eliminar</button>
        </form>