<h2 class="text-center">Eliminar artista</h2>
        <form id="delete-artist" method="post" action="deleteArtist">
            <div class="mb-3">
                <label for="artistSelect" class="form-label">Artista a eliminar</label>
                <select class="form-control" id="artistSelect" name="artist_id">
                    <option value="" disabled selected>Seleccione el artista</option>
                    <?= $optionsArtists ?>
                </select>
            </div>
            <button type="submit" class="btn btn-primary">Eliminar</button>
        </form>