<h2 class="text-center">Agregar artista</h2>
        <form method="post" action="newArtist">
            <div class="mb-3">
                <label for="artist_name" class="form-label">artist</label>
                <input type="text" class="form-control" id="artist_name" name="artist_name">
            </div>
            <div class="mb-3">
                <label for="nationality" class="form-label">Nacionalidad</label>
                <input type="text" class="form-control" id="nacionality" name="nationality">
            </div>
            <button type="submit" class="btn btn-primary">Agregar</button>
        </form>