<?php require 'templates/layout/header.php' ?>

<?php if($error) : ?>
    <div class='alert alert-danger' role='alert'>
        <?= $error ?>
    </div>
    <?php endif ?>

    <form method='post' action='login'>
  <div class="mb-3">
    <label for="email" class="form-label">Direccion de email</label>
    <input type="email" class="form-control" id="email" name="email" aria-describedby="emailHelp" required>
    <div id="emailHelp" class="form-text">Nunca compartiremos tu email con nadie.</div>
  </div>
  <div class="mb-3">
    <label for="password" class="form-label">contraseña</label>
    <input type="password" class="form-control" id="password" name="password" required>
  </div>
  
  <button type="submit" class="btn btn-primary">Login</button>
</form>   

<?php require 'templates/layout/footer.php' ?>
