<?php require 'templates/layout/header.php' ?>

<div class="container">

<?php if($error) : ?>
    <div class='alert alert-danger' role='alert'>
        <?= $error ?>
    </div>
    <?php endif ?>

    <form method='post' action='login' class="m-5">
  <div class="mb-3">
    <label for="user" class="form-label">Usuario</label>
    <input type="text" class="form-control" id="user" name="user" aria-describedby="userHelp" required>
    <div id="userHelp" class="form-text">Nunca compartiremos tus datos con nadie.</div>
  </div>
  <div class="mb-3">
    <label for="password" class="form-label">contraseña</label>
    <input type="password" class="form-control" id="password" name="password" required>
  </div>
  
  <button type="submit" class="btn btn-primary">Login</button>
  </form>
</div>

<?php require 'templates/layout/footer.php' ?>
