<?php require 'templates/layout/header.php'; ?>

<div class="album py-5">

    <div class="container">
        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
            <?php foreach($artists as $artist): ?>
                <div class="col">
                        <div class="card shadow-sm">
                        <img src="<?= $artist->img_artist ?>" alt="<?= $artist->artist_name ?>" class="bd-placeholder-img card-img-top" width="100%" height="100%">
                            <div class="card-body">
                                <h1 class="card-text"><?= $artist->artist_name ?><h1> 
                                <div class="btn-group">
                                    <a href="artist/<?= $artist->id_artist ?>" class="btn btn-sm btn-outline-secondary">view</a>
                                </div>
                            </div>
                        </div>
                </div>
            <?php endforeach; ?>
        </div>
    </div>
</div>;

<?php require 'templates/layout/footer.php'; ?>