<?php require 'templates/layout/header.php'; ?>

<div class="album py-5 bg-body-tertiary">

    <div class="container">
        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
            <?php foreach($artistas as $artista): ?>
                <div class="col">
                        <div class="card shadow-sm">
                            <svg class="bd-placeholder-img card-img-top" width="100%" height="225" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: Thumbnail" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#55595c"></rect><text x="50%" y="50%" fill="#eceeef" dy=".3em">Thumbnail</text></svg>
                            <div class="card-body">
                                <h1 class="card-text"><?= $artista->nombre_artista ?><h1> 
                                <div class="btn-group">
                                    <a href="artist/<?= $artista->id_artista ?>" class="btn btn-sm btn-outline-secondary">view</a>
                                </div>
                            </div>
                        </div>
                </div>
            <?php endforeach; ?>
        </div>
    </div>
</div>;

<?php require 'templates/layout/footer.php'; ?>