<?php require 'templates/layout/header.php'; ?>

<div class="container my-5">
    <h1 class="text-center mb-5"><i class="fas fa-users"></i> Acerca de nosotros y nuestra página</h1>
    <p class="text-center mb-5">Somos Nicolás Ledesma y Abril Crivaro, estudiantes de primer año de la carrera de TUDAI (Tecnicatura Universitaria en Desarrollo de Aplicaciones Informáticas).</p>
    <hr class="my-4">
    <h3 class="text-center mb-5"><i class="fas fa-project-diagram"></i> Nuestro Proyecto</h3>
    <p class="text-center mb-5">Nuestra página está diseñada para ofrecer un <em>ranking</em> global de artistas, donde se destacan las canciones más escuchadas según la cantidad de reproducciones. 
    El objetivo de este proyecto es proporcionar una experiencia visual y dinámica que permita a los usuarios descubrir artistas de manera individual, visualizando su música más popular. Cada artista cuenta con su propio espacio dentro de nuestra plataforma, donde se detallan sus canciones que han alcanzado el top de popularidad a nivel mundial.</p>

    <hr class="my-4">
    <h3 class="text-center mb-5"><i class="fas fa-project-diagram"></i> Objetivo del Proyecto</h3>
    <p class="text-center mb-5">Con este proyecto, buscamos explorar y aprender sobre desarrollo web, bases de datos y el análisis de datos en tiempo real, siempre desde nuestra pasión por la música y la tecnología.</p>
</div>
<?php require 'templates/layout/footer.php'; ?>