<?php require 'templates/layout/header.php' ?>

    <h1 class="text-center">Modificaciones</h1>
    <hr class="border border-danger border-2 opacity-50">
    <p class="text-center fs-3"></p>

    <div class="container">
    
    <?php require 'templates/form_addSong.phtml' ?>

    <hr class="border border-danger border-2 opacity-50">

    <?php require 'templates/form_modifySong.phtml'?>

    <hr class="border border-danger border-2 opacity-50">

    <?php require 'templates/form_deleteSong.phtml'?>

    <hr class="border border-danger border-2 opacity-50">

    <?php require 'templates/form_addArtist.phtml' ?>

    <hr class="border border-danger border-2 opacity-50">

    <?php require 'templates/form_modifyArtist.phtml'?>

    <hr class="border border-danger border-2 opacity-50">

    <?php require 'templates/form_deleteArtist.phtml'?>

    <hr class="border border-danger border-2 opacity-50">

    </div>
    

<?php require 'templates/layout/footer.php' ?>